/* d:/Projects/Ap-Bokifa-main/src/components/productsData.js */
// productsData.js

const ALL_PRODUCTS = [
  {
    id: 1,
    title: "The Wedding People",
    author: "ALICE HOFFMAN",
    description: "",
    price: 299.95,
    rating: 0,
    reviewCount: 0,
    discount: 15,
    saleEndDate: "2205-11-20T23:59:59", // 🚀 Timer added
    imageUrl: "/src/assets/the_wedding.webp",
    currentBestselling: false,
    isHighlight: true,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: false,
    category: "Fiction",
    format: "Hardcover",
    dateAdded: new Date("2024-03-01"), // New data for sorting
  },
  {
    id: 2,
    title: "Redemption Echo",
    author: "CATHY MCINTOSH",
    description: "",
    price: 249.95,
    rating: 0,
    reviewCount: 0,
    discount: 15,
    imageUrl: "/src/assets/RedemptionEcho.webp",
    currentBestselling: false,
    isHighlight: true,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: false,
    isWishlist: false,
    category: "Fantasy",
    format: "Paperback",
    dateAdded: new Date("2024-05-15"), // New data for sorting
  },
  {
    id: 3,
    title: "The Mighty Red",
    author: "LOUISE ERDRICH",
    description: "",
    price: 279.95,
    rating: 1,
    reviewCount: 1,
    discount: 15,
    imageUrl: "/src/assets/TheMightyRed.webp",
    currentBestselling: false,
    isHighlight: true,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: false,
    category: "Fiction",
    format: "Ebook",
    dateAdded: new Date("2024-01-20"), // New data for sorting
  },
  {
    id: 4,
    title: "James by Percival Everett",
    author: "PERCIVAL EVERETT",
    description: "",
    price: 299.95,
    rating: 0,
    reviewCount: 0,
    discount: 15,
    imageUrl: "/src/assets/James.webp",
    currentBestselling: false,
    isHighlight: true,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: false,
    category: "Fiction",
    format: "Audio cd",
    dateAdded: new Date("2024-04-10"),
  },
  {
    id: 5,
    title: "A Sorceress Comes to Call",
    author: "T. KINGFISHER",
    description: "",
    price: 319.95,
    rating: 0,
    reviewCount: 0,
    discount: 15,
    imageUrl: "/src/assets/ASorcerresComesToCall.webp",
    currentBestselling: false,
    isHighlight: true,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: false,
    isWishlist: false,
    category: "Fantasy",
    format: "Hardcover",
    dateAdded: new Date("2024-03-25"),
  },
  {
    id: 6,
    title: "The Last Thing He Told Me",
    author: "Laura Dave",
    description: "",
    price: 35.24,
    rating: 0,
    reviewCount: 0,
    discount: 15,
    imageUrl: "/src/assets/TheLastThingHeToldME.webp",
    currentBestselling: false,
    isHighlight: true,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: false,
    isWishlist: false,
    category: "Thriller",
    format: "Paperback",
    dateAdded: new Date("2023-10-01"),
  },
  {
    id: 7,
    title: "Another Great Book",
    author: "Ap Bokifa",
    description: "",
    price: 199.99,
    rating: 4,
    reviewCount: 120,
    discount: 15,
    imageUrl: "/src/assets/AnotherGreatBook.webp",
    currentBestselling: false,
    isHighlight: false,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: false,
    category: "Family",
    format: "Ebook",
    dateAdded: new Date("2024-02-14"),
  },
  // --- Current Bestselling Products ---
  {
    id: 8,
    title: "THE HOUSEMAID",
    author: "FREIDA MCFADDEN",
    description: "",
    price: 35.24,
    rating: 0,
    reviewCount: 0,
    discount: 15,
    imageUrl: "/src/assets/HouseMaid.webp",
    currentBestselling: true,
    isHighlight: false,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: false,
    isWishlist: false,
    category: "Thriller",
    format: "Audio cd",
    dateAdded: new Date("2023-11-20"),
  },
  {
    id: 9,
    title: "THE ILIAD",
    author: "HOMER (Translated by Emily Wilson)",
    description: "",
    price: 35.24,
    rating: 0,
    reviewCount: 0,
    discount: 15,
    imageUrl: "/src/assets/Iliad.webp",
    currentBestselling: true,
    isHighlight: false,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: false,
    isWishlist: false,
    category: "Classics",
    format: "Hardcover",
    dateAdded: new Date("2023-08-01"),
  },
  {
    id: 10,
    title: "ENTITLEMENT",
    author: "RUMAAN ALAM",
    description:
      "From the author of The Longest Ride and The Return comes a novel about the enduring legacy of first love, and the decisions that haunt...",
    price: 35.24,
    rating: 0,
    reviewCount: 0,
    discount: 15,
    saleEndDate: "2205-11-17T18:00:00", // 🚀 Timer added
    imageUrl: "/src/assets/ENTITLEMENT.webp",
    currentBestselling: true,
    isHighlight: false,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: false,
    isFeatured: true,
    isWishlist: false,
    category: "Fiction",
    format: "Paperback",
    dateAdded: new Date("2024-06-05"),
  },
  {
    id: 11,
    title: "MOUNT SWEET HOME",
    author: "SARAH PINSKER",
    description: "",
    price: 35.24,
    rating: 0,
    reviewCount: 0,
    discount: 15,
    imageUrl: "/src/assets/MOUNT_SWEET_HOME.webp",
    currentBestselling: true,
    isHighlight: false,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: false,
    category: "Family",
    format: "Ebook",
    dateAdded: new Date("2024-01-15"),
  },
  {
    id: 12,
    title: "ABSOLUTION",
    author: "JEFF VANDERMEER",
    description: "",
    price: 319.95,
    rating: 0,
    reviewCount: 0,
    discount: 15,
    imageUrl: "/src/assets/ABSOLUTION.webp",
    currentBestselling: true,
    isHighlight: false,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: false,
    isWishlist: false,
    category: "Thriller",
    format: "Audio cd",
    dateAdded: new Date("2024-04-01"),
  },
  {
    id: 13,
    title: "YELLOWFACE",
    author: "R. F. KUANG",
    description: "",
    price: 35.24,
    rating: 1,
    reviewCount: 1,
    discount: 15,
    imageUrl: "/src/assets/YELLOWFACE.webp",
    currentBestselling: true,
    isHighlight: false,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: false,
    category: "Horror",
    format: "Hardcover",
    dateAdded: new Date("2023-09-10"),
  },
  {
    id: 14,
    title: "THE WOMEN",
    author: "KRISTIN HANNAH",
    description: "",
    price: 35.24,
    rating: 0,
    reviewCount: 0,
    discount: 15,
    imageUrl: "/src/assets/THE_WOMEN.webp",
    currentBestselling: true,
    isHighlight: false,
    isHalfPrice: true,
    isSoldOut: false,
    isPickForYou: false,
    category: "Family",
    format: "Paperback",
    dateAdded: new Date("2024-02-28"),
  },
  {
    id: 15,
    title: "SO THIRSTY",
    author: "RACHEL HARRISON",
    description: "",
    price: 35.24,
    rating: 0,
    reviewCount: 0,
    discount: 15,
    imageUrl: "/src/assets/SO_THIRSTY.webp",
    currentBestselling: true,
    isHighlight: true,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: false,
    category: "Horror",
    format: "Ebook",
    dateAdded: new Date("2023-12-12"),
  },
  {
    id: 16,
    title: "Playground",
    author: "RICHARD POWERS",
    description: "",
    price: 35.24,
    rating: 0,
    reviewCount: 0,
    discount: 15,
    imageUrl: "/src/assets/Playground.webp",
    currentBestselling: true,
    isHighlight: false,
    isHalfPrice: true,
    isSoldOut: false,
    isPickForYou: false,
    category: "Family",
    format: "Audio cd",
    dateAdded: new Date("2024-03-10"),
  },
  {
    id: 17,
    title: "THE SAINT OF BRIGHT DOORS",
    author: "VAJRA CHANDRASEKERA",
    description: "",
    price: 35.24,
    rating: 0,
    reviewCount: 0,
    discount: 15,
    imageUrl: "/src/assets/THE_SAINT_OF_BRIGHT_DOORS.webp",
    currentBestselling: true,
    isHighlight: false,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: false,
    isWishlist: false,
    category: "Fantasy",
    format: "Hardcover",
    dateAdded: new Date("2024-05-20"),
  },
  // --- New Products Added (from Half price books and others) ---
  {
    id: 18,
    title: "BLACK SHEEP",
    author: "RACHEL HARRISON",
    description: "",
    price: 349.95,
    rating: 0,
    reviewCount: 0,
    discount: 15,
    imageUrl: "/src/assets/BLACK_SHEEP.webp",
    currentBestselling: false,
    isHighlight: false,
    isHalfPrice: true,
    isSoldOut: false,
    isPickForYou: false,
    isWishlist: false,
    category: "Horror",
    format: "Paperback",
    dateAdded: new Date("2024-06-15"),
  },
  {
    id: 19,
    title: "THE BOOK SWAP",
    author: "TESSA DİCKERS",
    description: "",
    price: 359.95,
    rating: 0,
    reviewCount: 0,
    discount: 15,
    imageUrl: "/src/assets/THE_BOOK_SWAP.webp",
    currentBestselling: false,
    isHighlight: false,
    isHalfPrice: true,
    isSoldOut: false,
    isPickForYou: false,
    isWishlist: false,
    category: "Fiction",
    format: "Ebook",
    dateAdded: new Date("2023-10-25"),
  },
  {
    id: 20,
    title: "ERASURE",
    author: "PERCIVAL EVERETT",
    description: "",
    price: 35.24,
    rating: 0,
    reviewCount: 0,
    discount: 15,
    imageUrl: "/src/assets/ERASURE.webp",
    currentBestselling: false,
    isHighlight: false,
    isHalfPrice: true,
    isSoldOut: false,
    isPickForYou: false,
    isWishlist: false,
    category: "Classics",
    format: "Audio cd",
    dateAdded: new Date("2024-05-05"),
  },
  {
    id: 21,
    title: "BY ANY OTHER NAME",
    author: "JODI PICOULT",
    description: "",
    price: 239.95,
    rating: 0,
    reviewCount: 0,
    discount: "",
    imageUrl: "/src/assets/BY_ANY_OTHER_NAME.webp",
    currentBestselling: false,
    isHighlight: false,
    isHalfPrice: true,
    isSoldOut: true,
    isPickForYou: false,
    isWishlist: false,
    category: "Family",
    format: "Hardcover",
    dateAdded: new Date("2024-06-10"),
  },
  {
    id: 22,
    title: "LOST AND LASSOED",
    author: "LYNNE GRAHAM",
    description: "",
    price: 259.95,
    rating: 5,
    reviewCount: 1,
    discount: "",
    imageUrl: "/src/assets/LOST_AND_LASSOED.webp",
    currentBestselling: false,
    isHighlight: false,
    isHalfPrice: true,
    isSoldOut: false,
    isPickForYou: false,
    isWishlist: false,
    category: "Romance",
    format: "Paperback",
    dateAdded: new Date("2024-06-01"),
  },
  // --- New Products Added from 'image_654a20.jpg' (Pick for you) ---
  {
    id: 23,
    title: "Harry Potter And The Sorcerer's Stone",
    author: "J. K. Rowling",
    description: "",
    price: 269.95,
    rating: 0,
    reviewCount: 0,
    discount: "",
    imageUrl: "/src/assets/harry.webp",
    currentBestselling: false,
    isHighlight: false,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: true,
    isWishlist: false,
    category: "Fantasy",
    format: "Ebook",
    dateAdded: new Date("2Z023-09-01"),
  },
  {
    id: 24,
    title: "Memoirs Of A Geisha",
    author: "ANDY WEIR",
    description: "",
    price: 289.95,
    rating: 0,
    reviewCount: 0,
    discount: "",
    imageUrl: "/src/assets/memoirs_of_a_geisha.webp",
    currentBestselling: false,
    isHighlight: false,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: true,
    isWishlist: false,
    category: "Romance",
    format: "Audio cd",
    dateAdded: new Date("2024-03-18"),
  },
  {
    id: 25,
    title: "Scattershot: Life, Music, Elton, and Me",
    author: "Bernie Taupin",
    description: "",
    price: 309.95,
    rating: 0,
    reviewCount: 0,
    discount: "",
    imageUrl: "/src/assets/Scattershot.webp",
    currentBestselling: false,
    isHighlight: false,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: true,
    isWishlist: false,
    category: "Biography",
    format: "Hardcover",
    dateAdded: new Date("2024-05-28"),
  },
  {
    id: 26,
    title: "The Catcher In The Rye",
    author: "J. D. Salinger",
    description: "",
    price: 329.95,
    rating: 0,
    reviewCount: 0,
    discount: "",
    imageUrl: "/src/assets/The_Catcher_In_The_Rye.webp",
    currentBestselling: false,
    isHighlight: false,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: true,
    isWishlist: false,
    category: "Classics",
    format: "Paperback",
    dateAdded: new Date("2023-11-01"),
  },
  {
    id: 27,
    title: "The City And Its Uncertain Walls: A Novel",
    author: "Haruki Murakami",
    description: "",
    price: 339.95,
    rating: 0,
    reviewCount: 0,
    discount: "",
    imageUrl: "/src/assets/The_City_And_Its_Uncertain_Walls.webp",
    currentBestselling: false,
    isHighlight: false,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: true,
    isWishlist: false,
    category: "Fantasy",
    format: "Ebook",
    dateAdded: new Date("2024-06-20"),
  },
  {
    id: 28,
    title: "The House Of The Spirits",
    author: "Isabel Allende",
    description: "",
    price: 29.95,
    rating: 0,
    reviewCount: 0,
    discount: "",
    imageUrl: "/src/assets/The_House_Of_The_Spirits.webp",
    currentBestselling: false,
    isHighlight: false,
    isHalfPrice: false,
    isSoldOut: false,
    isPickForYou: true,
    isWishlist: false,
    category: "Fiction",
    format: "Hardcover",
    dateAdded: new Date("2023-12-05"),
  },
];

// Export the full list as the default export
export default ALL_PRODUCTS;
